# Generated by Django 5.2.4 on 2026-03-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='Email',
            field=models.CharField(blank=True, null=True),
        ),
    ]
