# Generated by Django 5.2.4 on 2026-03-30 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='medicine_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prescription'),
        ),
    ]
