# Generated by Django 5.2.4 on 2026-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bill_doctor_name_bill_medicine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Finished', 'Finished')], default='Pending', max_length=20),
        ),
    ]
