# Generated by Django 5.2.4 on 2026-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_health_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
