# Generated by Django 5.2.4 on 2026-03-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
