# Generated by Django 5.2.4 on 2026-03-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_health_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
