# Generated by Django 5.2.4 on 2026-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_health_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='no',
        ),
        migrations.AddField(
            model_name='health',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
